;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        LaTeX-babel-insert-hyphen
        LaTeX-insert-left-brace
        TeX-insert-backslash
        TeX-insert-dollar
        TeX-insert-sub-or-superscript
        TeX-newline
        beginning-of-visual-line
        c-electric-brace
        c-electric-colon
        c-electric-paren
        c-electric-semi&comma
        c-electric-star
        dove-backward-kill-word
        dove-forward-kill-word
        end-of-visual-line
        enlarge-window-horizontally
        forward-sexp
        kill-region
        org-force-self-insert
        org-return
        orgtbl-hijacker-command-100
        orgtbl-hijacker-command-102
        orgtbl-self-insert-command
        reindent-then-newline-and-indent
        smex
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        c-electric-lt-gt
        mouse-drag-secondary
        org-self-insert-command
        ))
